.PHONY: clean All

All:
	@echo "----------Building project:[ BT - Debug ]----------"
	@cd "BT" && "$(MAKE)" -f  "BT.mk"
clean:
	@echo "----------Cleaning project:[ BT - Debug ]----------"
	@cd "BT" && "$(MAKE)" -f  "BT.mk" clean
